blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.index,name='index'),
]

myfashion/urls.py
from django.contrib import admin
from django.urls import path
import blog.views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('', blog.views.index, name='index'),
    #path('upload/',blog.views.upload,name='upload'),
    path('clothes/',blog.views.cloth_list,name='cloth_list'),
    path('upload/',blog.views.upload_cloth,name='upload_cloth'),
    path('clothes/save/',blog.views.save_cloth,name='save_cloth'),
    path('clothes/result/<int:cloth_id>/',blog.views.result,name='result'),
    path('test/', blog.views.Rec, name='test'),
    path('clothes/Top/',blog.views.cloth_list1,name='cloth_list1'),
    path('clothes/Bottom/',blog.views.cloth_list2,name='cloth_list2'),
    path('clothes/Dress',blog.views.cloth_list3,name='cloth_list3'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse_lazy
from django.shortcuts import reverse
# Create your models here.

cloth_category = {
    ('Shirt', 'Shirt'),
    ('Blouse', 'Blouse'),
    ('Pants', 'Pants'),
    ('Skirt', 'Skirt')
}

cloth_label = (
    ('T', 'Top'),
    ('B', 'Bottom'),
    ('D', 'Dress'),
)

class Cloth(models.Model):
    closet = models.ImageField(upload_to='clothes/closets/',null=True,blank=True)
    category = models.CharField(max_length=50 , null=True, default='self')
    label = models.CharField(choices=cloth_label, max_length=1, null=True, default="T")
    category_num = models.IntegerField(default=0)

class Recommend(models.Model):
    index = models.IntegerField(default=0, primary_key=True)
    Path = models.CharField(max_length=100)
    label_T = models.IntegerField(default=0)
    label_B = models.IntegerField(default=0)

class Selection(models.Model):
    v_id = models.IntegerField(default=0)
    v_up = models.IntegerField(default=0)
    v_down = models.IntegerField(default=0)

    def __int__(self):
        return self.v_up

blog/forms.py
from django import forms
from .models import Cloth

####

class ClothForm(forms.ModelForm):
    class Meta:
        model = Cloth
        fields = ('closet','category','label','category_num')

blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.core.files.storage import FileSystemStorage
from keras.models import load_model
from PIL import Image
import numpy as np
import sqlite3

from .models import Selection
from .forms import ClothForm
from .models import Cloth
from .models import Recommend
# render는 데이터 값을 반아온뒤 html로 데이터를 보내기 위한 함수

# Create your views here.

#결과 값을 render 함수를 통해 요청을 index.html 문서로 리턴
def index(request):
    return render(request, 'index.html')



def upload(request):
    context = {}
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name,uploaded_file)
        context['url'] = fs.url(name)
    return render(request,'upload.html',context)




def upload_cloth(request):
    if request.method == 'POST':
        form = ClothForm(request.POST, request.FILES)
        request.session["closet_file"] = str(request.FILES['closet'])

        print("세션 성공", request.session["closet_file"])
        if form.is_valid():
            form.save()
            category = AI_check(request.session["closet_file"])
            request.session["category"] = category
            print("AI Check result :", category)
            return render(request,'save_cloth.html')
    else:
        form = ClothForm()
        return render(request, 'upload_cloth.html',{
            'form' : form
        })

def save_cloth(request):
    if request.method == 'POST':
        conn = sqlite3.connect("C:/Django/pjt/myfashion/db.sqlite3")
        c = conn.cursor()

        print( request.POST["category"] )
        label, num = category_to_label_and_num(request.POST["category"])
        category = "'"+request.POST["category"]+"','"+label+"','"+num+"'"
        path = "'"+"clothes/closets/"+request.session["closet_file"]+"'"
        update = "UPDATE blog_cloth SET (Category, label, category_num) = (" + category + ") WHERE closet = "+path
        print(update)
        c.execute(update)
        conn.commit()

        return redirect('cloth_list')
    else:
        form = ClothForm()
    return render(request, 'save_cloth.html', {
        'form': form
    })

def AI_check(file):
    X =[]
    categories = ['long_blouse_check', 'long blouse_none', 'long blouse_pattern', 'long dress_long sleeves',
                  'long dress_short sleeves', 'long pants_jean', 'long pants_cotton', 'long shirt_check',
                  'long shirt_none', 'long shirt_pattern', 'long skirt_A', 'long skirt_asymmetric',
                  'long skirt_H', 'long sleeve_none', 'long sleeve_print', 'long sleeve_stripe',
                  'mini dress_long sleeves', 'mini dress_short sleeves', 'short blouse_check', 'short blouse_none',
                  'short blouse_pattern', 'short pants_jean', 'short pants_cotton', 'short shirt_check',
                  'short shirt_none', 'short shirt_pattern', 'short skirt_A', 'short skirt_asymmetric',
                  'short skirt_H', 'short sleeve_none', 'short sleeve_print', 'short sleeve_stripe',
                  'sleeveless_none', 'sleeveless_print', 'sleeveless_stripe']


    model = load_model('C:/Django/pjt/myfashion/blog/fashion_best_model.h5')

    img_path = ["C:/Django/pjt/myfashion/media/clothes/base.png",
                "C:/Django/pjt/myfashion/media/clothes/closets/" + str(file)]
    print(str(file))

    for fname in img_path:
        img = Image.open(fname)
        img = img.convert("RGB")
        img = img.resize((64, 64))
        in_data = np.asarray(img)
        in_data = in_data.astype("float") / 256
        X.append(in_data)

    X = np.array(X)
    pre = model.predict(X)

    for i, p in enumerate(pre):
        y = p.argmax()
        category = categories[y]
    return category

def category_to_label_and_num(category):

    categories = ['long shirt_none', 'long shirt_check', 'long shirt_pattern', 'short shirt_none', 'short shirt_check', 'short shirt_pattern',
                  'long blouse_none', 'long_blouse_check', 'long blouse_pattern', 'short blouse_none', 'short blouse_check', 'short blouse_pattern',
                  'long sleeve_none', 'long sleeve_stripe', 'long sleeve_print', 'short sleeve_none', 'short sleeve_stripe', 'short sleeve_print',
                  'sleeveless_none', 'sleeveless_stripe', 'sleeveless_print', 'long pants_jean', 'long pants_cotton',
                  'short pants_jean', 'short pants_cotton', 'long skirt_H', 'long skirt_A', 'long skirt_asymmetric',
                  'short skirt_H', 'short skirt_A', 'short skirt_asymmetric','long dress_long sleeves', 'long dress_short sleeves',
                  'short dress_long sleeves', 'short dress_short sleeves']
    i=0
    for cate in categories:
        i = i+1
        if category == cate:
            num = str(i)
            break

    for cate in categories[0:21]:
        if category == cate:
            label = "T"
            return label, num

    for cate in categories[21:31]:
        if category == cate:
            label = "B"
            return label, num

    for cate in categories[31:]:
        if category == cate:
            label = "D"
            return label, num

def cloth_list(request):
    clothes = Cloth.objects.all()
    ##############
    qs2 = Selection.objects.get(v_id=1)
    qs2.v_id = 1
    qs2.v_up = 0
    qs2.v_down = 0

    qs2.save()
    ###########
    return render(request,'cloth_list.html',{
        'clothes' : clothes,
    })



def result(request,cloth_id ):
    choices = get_object_or_404(Cloth, pk = cloth_id )
    if choices.label == 'T':
        qs3 = Selection.objects.get(v_id=1)
        qs3.v_id=1
        qs3.v_up=choices.category_num
        qs3.v_up_img=choices.closet.url
        qs3.save()

    if choices.label == 'B':
        qs3 = Selection.objects.get(v_id=1)
        qs3.v_id=1
        qs3.v_down=choices.category_num
        qs3.v_down_img = choices.closet.url
        qs3.save()

    rT = Cloth.objects.filter(label='B')
    rB = Cloth.objects.filter(label='T')



    return render(request,'result.html',{
        'choices' : choices,
        'rT': rT,
        'rB': rB
    })


def Rec(request):
    rec = Recommend.objects.all()
    rec_row = len(rec)

    print("***************",rec_row)
    qs = Selection.objects.get(v_id=1)
    if qs.v_up !=0 :
        codi = Recommend.objects.filter(label_T= qs.v_up).values()& Recommend.objects.filter(label_B= request.POST["category_num"]).values()

    if qs.v_down !=0 :
        codi = Recommend.objects.filter(label_T=request.POST["category_num"]).values() & Recommend.objects.filter(label_B= qs.v_down).values()

    return render(request,'test.html',{
        'codi' : codi,
    })


def cloth_list1(request):
    clothes = Cloth.objects.filter(label='T')
    ##############
    qs2 = Selection.objects.get(v_id=1)
    qs2.v_id = 1
    qs2.v_up = 0
    qs2.v_down = 0

    qs2.save()
    ###########
    return render(request,'cloth_list.html',{
        'clothes' : clothes,
    })

def cloth_list2(request):
    clothes = Cloth.objects.filter(label='B')
    ##############
    qs2 = Selection.objects.get(v_id=1)
    qs2.v_id = 1
    qs2.v_up = 0
    qs2.v_down = 0

    qs2.save()
    ###########
    return render(request,'cloth_list.html',{
        'clothes' : clothes,
    })

def cloth_list3(request):
    clothes = Cloth.objects.filter(label='D')
    ##############
    qs2 = Selection.objects.get(v_id=1)
    qs2.v_id = 1
    qs2.v_up = 0
    qs2.v_down = 0

    qs2.save()
    ###########
    return render(request,'cloth_list.html',{
        'clothes' : clothes,
    })

blog/templates/cloth_list.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>AI_FASHION</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      @import url('https://fonts.googleapis.com/css2?family=Gugi&family=Kalam&display=swap');
      p1{
          font-size : 3em;
          font-family: 'Gugi', cursive;
      }


      *{
            box-sizing: border-box;
        }
       .btn1{
            padding: 2px 50px;
            margin: 2px 10px ;
            color: #646363;
            font-family: 'Kalam', cursive;
            text-transform: uppercase;
            text-align: center;
            position: relative;
            text-decoration: none;
            display:inline-block;
       }
    .btn1::before {
            content: '';
            position: absolute;
            bottom: 50%;
            left: 0px;
            width: 100%;
            height: 2.3px;
            background: #fbceb1;
            text-decoration: none;
            color : #fff;
            display: block;
            -webkit-transform-origin: left top;
            -ms-transform-origin: left top;
            transform-origin: left top;
            -webkit-transform: scale(0, 1);
            -ms-transform: scale(0, 1);
            transform: scale(0, 1);
            -webkit-transition: transform 0.4s cubic-bezier(1, 0, 0, 1);
            transition: transform 0.4s cubic-bezier(1, 0, 0, 1)
    }

    .btn1:hover::before {
             text-decoration: none;
            -webkit-transform-origin: right top;
            -ms-transform-origin: right top;
             transform-origin: right top;
            -webkit-transform: scale(1, 1);
            -ms-transform: scale(1, 1);
             transform: scale(1, 1)
    }
    a:link { color: black; text-decoration: none;}
    a:visited { color: black; text-decoration: none;}
    a:hover { color: black; text-decoration: underline; font-weight: 300; font-size : 1.3em;}

    .btn7{
            width:100px;
            float : left;
            padding : 0px 5px 0px 5px
            margin: 0px 20px 0px 20px ;
            color: #000;
            font-family: 'Kalam', cursive;
            text-transform: uppercase;
            position: relative;
            text-decoration: none;
            display:inline-block;
    }
    .btn7 {
            box-shadow: inset 000px 0px 0px 0px #fbceb1;
            -webkit-transition: all 0.6s cubic-bezier(.9, .24, .40, 1);
            transition: all 0.6s cubic-bezier(.9, .24, .40, 1)
    }

    .btn7::before {
            content: '';
            width: 100%;
            height: 0%;
            display: block;
            background: #80ffd3;
            position: absolute;
            left: 0%;
            opacity: 0;
            top: 0;
            z-index: -1;
            -webkit-transition: height .4s cubic-bezier(0.9, 1, 0.32, 1), opacity .1s ease;
            transition: height .4s cubic-bezier(0.9, 1, 0.32, 1), opacity .1s ease;
       }

    .btn7:hover::before {
            opacity: 1;
            height: 100%;
    }
    .btn7:hover {
            box-shadow: inset 00px 100px 0px 0px #fbceb1;
            color: #ffffff;
    }
    .bar-anchor{
            padding: 20px 10px;
            margin: 0px 20px 0px 20px ;
            color: #fff;
            font-family: sans-serif;
            text-transform: uppercase;
             text-align: center;
            position: relative;
            text-decoration: none;
            display:inline-block;
            overflow:hidden;
        /*          border:1px solid #6098FF; */
    }
    .bar-anchor span{
         background:#00002E;
         width:100%;
        position:relative;
        padding:10px 70px;
        -moz-transition: all .65s cubic-bezier(0.77, 0, 0.175, 1);
        -o-transition: all .65s cubic-bezier(0.77, 0, 0.175, 1);
        -webkit-transition: all .65s cubic-bezier(0.77, 0, 0.175, 1);
        transition: all .65s cubic-bezier(0.77, 0, 0.175, 1);
        /*   border:1px solid #6098FF;  */
    }
    .transition-bar{
        position: absolute;
        top: 0;
        left: 0%;
        width: 0;
        height: 100%;
        background: #fbceb1;
        z-index:-1;
    /*     -ms-transform: skewX(-20deg);
        -webkit-transform: skewX(-20deg);
        transform: skewX(-20deg); */
    }
    .bar-anchor:hover span{
            color: #fbceb1!important;
    }
    .bar-anchor:hover .transition-bar{
        width:120%;
        left:110%;
        -moz-transition: all .65s cubic-bezier(0.77, 0, 0.175, 1);
        -o-transition: all .65s cubic-bezier(0.77, 0, 0.175, 1);
        -webkit-transition: all .65s cubic-bezier(0.77, 0, 0.175, 1);
        transition: all .65s cubic-bezier(0.77, 0, 0.175, 1);
        }
     header{
            position: fixed;
            left: 0;
            right: 0;
            top: 0;
            height: 40rem;
            padding: 1rem;
            background: white;
            line-height: 4rem;
            text-align: center;
     }
     main {
             padding: 1rem;
            height: 100%;
     }
     body {
            padding-top: 280px;
     }

     body, html {
              height: 200%;
     }
     .box{
        float : left;
        width : 100%;
        height : 7px;
        margin : 2px 30px 5px 80px ;
        text-align: center;
     }
     .wrapper{
            text-align: center;
     }
     .card{
            display: inline-block;
            width: 200px;
            height: 260px;
            border: 1px solid #cecece;
            text-align: center;
            margin-top: 5px;
      }

    .card img{
      width: 180px;
      height: 240px;
      border: 1px solid #cecece;
      margin-top: 10px;
    }
   </style>
</head>

<body>
    <header>
    <img src="/media/clothes/closets/logo.PNG" style="display: block; margin: 0 auto; width:230px; height:120px;" >
    <div style="padding:10px;">
    </div>
    <p1>AI! 코디를 부탁해</p1>
    <p>
      <a href="{% url 'cloth_list' %}" class="btn1" style="text-decoration:none">MY CLOSET</a>
      <a href="{% url 'upload_cloth' %}" class="btn1" style="text-decoration:none">NEW CLOTH</a>
    </p>
    </header>

    <div style="padding:10px;">
    </div>

    <main>
        <div class="box">
        <p>
        <a href="{% url 'cloth_list' %}" class="btn7" style="text-decoration:none">ALL</a>
        <a href="{% url 'cloth_list1' %}" class="btn7" style="text-decoration:none">TOP</a>
        <a href="{% url 'cloth_list2' %}" class="btn7" style="text-decoration:none">BOTTOM</a>
        <a href="{% url 'cloth_list3' %}" class="btn7" style="text-decoration:none">DRESS</a>
        </p>
        </div>
        <div style="padding:30px;">
        </div>
        <div class="container">
            <div class="row">
                {% for cloth in clothes %}
                <div class="col-3">
                    <div class="card">
                        <a href="{% url 'result' cloth.id %}">
                            <img src="{{ cloth.closet.url }}" class="card-img-top" />
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>


    </main>

</body>
</html>

blog/templates/save_cloth.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>AI_FASHION</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.8.0.min.js"></script>

<script type="text/javascript">
    $(function(){
        $("#cate").change(function(){
            var state = $("#cate").val();
            if (state == "auto"){
                $("#cate2 > option").remove();
                $("#id_category").val("{{ request.session.category }}");
            }else if(state == "top"){
                $("#cate2 > option").remove();
                $("#cate2").append('<option value="">상의 선택</option>');
                $("#cate2").append('<option value="long blouse_check">long blouse_check</option>');
                $("#cate2").append('<option value="long blouse_none">long blouse_none</option>');
                $("#cate2").append('<option value="long blouse_pattern">long blouse_pattern</option>');
                $("#cate2").append('<option value="long shirt_check">long shirt_check</option>');
                $("#cate2").append('<option value="long shirt_none">long shirt_none</option>');
                $("#cate2").append('<option value="long shirt_pattern">long shirt_pattern</option>');
                $("#cate2").append('<option value="long sleeve_none">long sleeve_none</option>');
                $("#cate2").append('<option value="long sleeve_print">long sleeve_print</option>');
                $("#cate2").append('<option value="long sleeve_stripe">long sleeve_stripe</option>');
                $("#cate2").append('<option value="short blouse_check">short blouse_check</option>');
                $("#cate2").append('<option value="short blouse_none">short blouse_none</option>');
                $("#cate2").append('<option value="short blouse_pattern">short blouse_pattern</option>');
                $("#cate2").append('<option value="short shirt_check">short shirt_check</option>');
                $("#cate2").append('<option value="short shirt_none">short shirt_none</option>');
                $("#cate2").append('<option value="short shirt_pattern">short shirt_pattern</option>');
                $("#cate2").append('<option value="short sleeve_none">short sleeve_none</option>');
                $("#cate2").append('<option value="short sleeve_print">short sleeve_print</option>');
                $("#cate2").append('<option value="short sleeve_stripe">short sleeve_stripe</option>');
                $("#cate2").append('<option value="sleeveless_none">sleeveless_none</option>');
                $("#cate2").append('<option value="sleeveless_print">sleeveless_print</option>');
                $("#cate2").append('<option value="sleeveless_stripe">sleeveless_stripe</option>');
            }else if(state == "bottom"){
                $("#cate2 > option").remove();
                $("#cate2").append('<option value="">하의 선택</option>');
                $("#cate2").append('<option value="long pants_jean">long pants_jean</option>');
                $("#cate2").append('<option value="long pants_cotton">long pants_cotton</option>');
                $("#cate2").append('<option value="long skirt_A">long skirt_A</option>');
                $("#cate2").append('<option value="long skirt_asymmetric">long skirt_asymmetric</option>');
                $("#cate2").append('<option value="long skirt_H">long skirt_H</option>');
                $("#cate2").append('<option value="short pants_jean">short pants_jean</option>');
                $("#cate2").append('<option value="short pants_cotton">short pants_cotton</option>');
                $("#cate2").append('<option value="short skirt_A">short skirt_A</option>');
                $("#cate2").append('<option value="short skirt_asymmetric">short skirt_asymmetric</option>');
                $("#cate2").append('<option value="short skirt_H">short skirt_H</option>');
            }else if(state == "onepice"){
                $("#cate2 > option").remove();
                $("#cate2").append('<option value="">원피스 선택</option>');
                $("#cate2").append('<option value="long dress_long sleeves">long dress_long sleeves</option>');
                $("#cate2").append('<option value="long dress_short sleeves">long dress_short sleeves</option>');
                $("#cate2").append('<option value="short dress_long sleeves">short dress_long sleeves</option>');
                $("#cate2").append('<option value="short dress_short sleeves">short dress_short sleeves</option>');
            }


        });

        $("#cate2").change(function(){
                $("#id_category").val($("#cate2").val());
        });


    });
</script>

    <style>
      @import url('https://fonts.googleapis.com/css2?family=Gugi&family=Kalam&family=Hi+Melody&display=swap');
      p1{
          font-size : 2.5em;
          font-family: 'Gugi', cursive;
      }
      p2{
         font-size : 2em;
         font-family: 'Hi Melody', cursive;
      }
      *{
            box-sizing: border-box;
        }
       .btn1{
            padding: 2px 50px;
            margin: 2px 10px ;
            color: #646363;
            font-family: 'Kalam', cursive;
            text-transform: uppercase;
            text-align: center;
            position: relative;
            text-decoration: none;
            display:inline-block;
       }
    .btn1::before {
            content: '';
            position: absolute;
            bottom: 50%;
            left: 0px;
            width: 100%;
            height: 2.3px;
            background: #fbceb1;
            text-decoration: none;
            color : #fff;
            display: block;
            -webkit-transform-origin: left top;
            -ms-transform-origin: left top;
            transform-origin: left top;
            -webkit-transform: scale(0, 1);
            -ms-transform: scale(0, 1);
            transform: scale(0, 1);
            -webkit-transition: transform 0.4s cubic-bezier(1, 0, 0, 1);
            transition: transform 0.4s cubic-bezier(1, 0, 0, 1)
    }

    .btn1:hover::before {
             text-decoration: none;
            -webkit-transform-origin: right top;
            -ms-transform-origin: right top;
             transform-origin: right top;
            -webkit-transform: scale(1, 1);
            -ms-transform: scale(1, 1);
             transform: scale(1, 1)
    }
    a:link { color: black; text-decoration: none;}
    a:visited { color: black; text-decoration: none;}
    a:hover { color: black; text-decoration: underline; font-weight: 300; font-size : 1.3em;}
        .box {

        }
        .container {
            display: flex;
            flex-direction: column;
            border: none;
        }
        .content {
            display: flex; // content로 감싸고 flex를 줬습니다.
            justify-content: center;
        }

   </style>
</head>
    <div class="container">
        <div class="content">
            <div class="box left">
                <img src="/media/clothes/closets/logo.PNG"
                     style="display: block; width:180px; height:100px; margin : 20px 80px 30px 220px" >
            </div>
            <div class="box center" style="text-align: center; margin : 40px 0px 30px 20px">
                 <p1>  AI! 코디를 부탁해   </p1>
                 <p>
                    <a href="{% url 'cloth_list' %}" class="btn1" style="text-decoration:none; margin : 20px 5px  ">MY CLOSET</a>
                    <a href="{% url 'upload_cloth' %}" class="btn1" style="text-decoration:none;">NEW CLOTH</a>
                 </p>
            </div>
        </div>
        <div class="box footer" style="text-align: center;">
    <p2> 새로운 옷을 추가해 보세요 </p2>
    <form method="post" enctype="multipart/form-data"  action="{% url 'save_cloth' %}">
    {% csrf_token %}
    <h5>
        <label for="id_closet" style="font-family: 'Hi Melody', cursive;">선택한 파일:</label>
        <label name="closet" id="id_closet" style="font-family: 'Hi Melody', cursive;">{{ request.session.closet_file }}</label>
    </h5>
    <img src = "../../media/clothes/closets/{{ request.session.closet_file }}" alt="{{ request.session.closet_file }}" style="width:200px;"/>
    <p>
        <label for="id_category" style=" font-size : 1.5em;font-family: 'Hi Melody', cursive;">Category:</label>
        <input class="category_type" type="text" name="category" maxlength="50" required id="id_category" value="{{ request.session.category }}"
            style="height : 30px; text-align: center; font-size : 1.4em; font-family: 'Hi Melody', cursive;"/>
         <select name="cate" id="cate" style=" height : 30px; font-size : 1.3em; font-family: 'Hi Melody', cursive;">
            <option value="auto">자동확인</option>
            <option value="top">상의</option>
            <option value="bottom">하의</option>
            <option value="onepice">원피스</option>
        </select>
        <select name="cate2" id="cate2">
        </select>
    </p>
    <input type="submit" class="btn btn-dark" value="저장" id="save"/>
    </form>
        </div>
    </div>

</div>>
</html>